import express from "express";
import fetch from "node-fetch";

const app = express();
app.use(express.json());

// ⚠️ HARD-CODED TOKEN (rotate later)
const BOT_TOKEN = "8011194756:AAGyKwXUjKvamH3hzsMNNwiQW_N8ChfA608";
const TELEGRAM_API = `https://api.telegram.org/bot${BOT_TOKEN}`;

// Pollinations APIs
const TEXT_API = "https://text.pollinations.ai/";
const IMAGE_API = "https://image.pollinations.ai/prompt/";

// Simple in-memory chat memory
const memory = new Map();

// System prompt
function systemPrompt() {
  return `
You are Black Chat.
Creator: Mohiuddin Abdul Kadir Dhrubo.
Reply in Bangla if input is Bangla, otherwise English.
Style: short, friendly, human, not robotic.
Never mention Pollinations or AI sources.
`.trim();
}

// Detect Bangla
function isBangla(text) {
  return /[\u0980-\u09FF]/.test(text);
}

// Clean branding
function cleanText(text) {
  return text
    .replace(/pollinations/gi, "")
    .replace(/powered by.*ai/gi, "")
    .replace(/generated by.*ai/gi, "")
    .trim();
}

// Detect image request
function isImageRequest(text) {
  return /^(imagine|draw|generate|create|make).*(image|photo|picture|art)/i.test(text)
      || text.toLowerCase().startsWith("imagine");
}

// Telegram webhook
app.post("/webhook", async (req, res) => {
  const msg = req.body.message;
  if (!msg || !msg.text) return res.sendStatus(200);

  const chatId = msg.chat.id;
  const userText = msg.text.trim();

  // Init memory
  if (!memory.has(chatId)) memory.set(chatId, []);
  const chatMem = memory.get(chatId);

  try {
    // 🎨 IMAGE GENERATION
    if (isImageRequest(userText)) {
      const prompt = encodeURIComponent(
        `${userText}, cinematic lighting, ultra detailed, sharp focus, masterpiece`
      );

      const seed = Math.floor(Math.random() * 99999);
      const imgUrl =
        `${IMAGE_API}${prompt}` +
        `?width=768&height=768&model=flux&seed=${seed}&nologo=true`;

      await fetch(`${TELEGRAM_API}/sendPhoto`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          chat_id: chatId,
          photo: imgUrl,
          caption: isBangla(userText)
            ? "🖼️ ছবি তৈরি হয়েছে"
            : "🖼️ Image generated"
        })
      });

      return res.sendStatus(200);
    }

    // 🧠 TEXT CHAT
    const messages = [
      { role: "system", content: systemPrompt() },
      ...chatMem.slice(-6),
      { role: "user", content: userText }
    ];

    const aiRes = await fetch(TEXT_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        messages,
        model: "openai",
        seed: Math.floor(Math.random() * 10000)
      })
    });

    let reply = await aiRes.text();
    reply = cleanText(reply);

    // Save memory
    chatMem.push({ role: "user", content: userText });
    chatMem.push({ role: "assistant", content: reply });

    await fetch(`${TELEGRAM_API}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: chatId,
        text: reply
      })
    });

  } catch (err) {
    await fetch(`${TELEGRAM_API}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: chatId,
        text: "⚠️ Error. Try again later."
      })
    });
  }

  res.sendStatus(200);
});

// Health check
app.get("/", (_, res) => res.send("Black Chat Telegram Bot running"));

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Server running"));