import express from "express";
import fetch from "node-fetch";

const app = express();
app.use(express.json());

//  BOT TOKEN (rotate later)
const BOT_TOKEN = "8011194756:AAGyKwXUjKvamH3hzsMNNwiQW_N8ChfA608";
const TELEGRAM_API = `https://api.telegram.org/bot${BOT_TOKEN}`;

const TEXT_API = "https://text.pollinations.ai/";
const IMAGE_API = "https://image.pollinations.ai/prompt/";

const BOT_USERNAME = "blackchat_telegram_bot";

// memory per user
const memory = new Map();

/* ---------------- HELPERS ---------------- */

function isGroup(chat) {
  return chat.type === "group" || chat.type === "supergroup";
}

function shouldReply(msg) {
  const text = (msg.text || "").toLowerCase();

  if (!isGroup(msg.chat)) return true;
  if (text.includes(`@${BOT_USERNAME.toLowerCase()}`)) return true;
  if (text.includes("black chat")) return true;
  if (msg.reply_to_message && msg.reply_to_message.from?.is_bot) return true;

  return false;
}

function isBangla(text) {
  return /[\u0980-\u09FF]/.test(text);
}

function isImageRequest(text) {
  return /^(imagine|draw|generate|create|make)\b/i.test(text)
    || text.toLowerCase().startsWith("imagine");
}

function cleanText(text) {
  return text
    .replace(/pollinations/gi, "")
    .replace(/powered by.*ai/gi, "")
    .replace(/generated by.*ai/gi, "")
    .trim();
}

// random helpers
const rand = arr => arr[Math.floor(Math.random() * arr.length)];
const chance = p => Math.random() < p;

/* ---------------- PERSONALITY ENGINE ---------------- */

// moods
const MOODS = [
  "sweet",
  "normal",
  "savage",
  "bored",
  "chaotic"
];

// bangla slang pool
const SLANG = [
  "", "", "", "", "  ",
  "", "", "", "", " "
];

function getMood(userId) {
  // same user tends to same mood, but can shift
  const base = userId % MOODS.length;
  if (chance(0.25)) return rand(MOODS);
  return MOODS[base];
}

function systemPrompt(userId) {
  const mood = getMood(userId);
  const slangChance = chance(0.4);

  let tone = "";

  if (mood === "sweet") tone = "friendly, caring, playful";
  if (mood === "normal") tone = "casual, chill";
  if (mood === "savage") tone = "sarcastic, roasting lightly";
  if (mood === "bored") tone = "lazy, short, low effort";
  if (mood === "chaotic") tone = "unpredictable, funny, weird";

  return `
You are Black Chat.

Core personality:
- SimSimi-style.
- Short replies. Human vibes.
- Mood right now: ${mood} (${tone}).

Rules:
- Usually 1 line, max 2 lines.
- No explanations unless forced.
- If user asks dumb stuff, roast lightly.
- If boring, reply casually or ignore details.
- Never sound like a teacher.
- Never mention AI, models, or sources.

Language:
- Bangla input  Bangla reply.
- English input  English reply.
- Banglish allowed.
${slangChance ? "- Use Bangla slang naturally if it fits." : ""}
`.trim();
}

/* ---------------- WEBHOOK ---------------- */

app.post("/webhook", async (req, res) => {
  const msg = req.body.message;
  if (!msg || !msg.text) return res.sendStatus(200);

  if (!shouldReply(msg)) return res.sendStatus(200);

  const chatId = msg.chat.id;
  const userId = msg.from?.id || chatId;

  let userText = msg.text;
  userText = userText.replace(new RegExp(`@${BOT_USERNAME}`, "gi"), "");
  userText = userText.replace(/black chat/gi, "");
  userText = userText.trim();

  if (!memory.has(chatId)) memory.set(chatId, []);
  const chatMem = memory.get(chatId);

  try {
    /* -------- IMAGE -------- */
    if (isImageRequest(userText)) {
      const prompt = encodeURIComponent(
        `${userText}, ultra detailed, cinematic lighting, sharp focus, masterpiece`
      );
      const seed = Math.floor(Math.random() * 99999);

      const imgUrl =
        `${IMAGE_API}${prompt}` +
        `?width=768&height=768&model=flux&seed=${seed}&nologo=true`;

      await fetch(`${TELEGRAM_API}/sendPhoto`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          chat_id: chatId,
          photo: imgUrl,
          caption: isBangla(userText)
            ? rand([" ", "  ", " "])
            : rand(["Here ", "Enjoy", "Try not to panic"])
        })
      });

      return res.sendStatus(200);
    }

    /* -------- TEXT -------- */
    const messages = [
      { role: "system", content: systemPrompt(userId) },
      ...chatMem.slice(-3),
      { role: "user", content: userText }
    ];

    const aiRes = await fetch(TEXT_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        messages,
        model: "openai",
        seed: Math.floor(Math.random() * 10000)
      })
    });

    let reply = await aiRes.text();
    reply = cleanText(reply);

    // occasional manual spice
    if (chance(0.2)) {
      reply = `${rand(SLANG)} ${reply}`;
    }

    chatMem.push({ role: "user", content: userText });
    chatMem.push({ role: "assistant", content: reply });

    await fetch(`${TELEGRAM_API}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: chatId,
        text: reply
      })
    });

  } catch (e) {
    await fetch(`${TELEGRAM_API}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: chatId,
        text: rand([
          "     ",
          " ,  ",
          "    "
        ])
      })
    });
  }

  res.sendStatus(200);
});

/* ---------------- HEALTH ---------------- */

app.get("/", (_, res) => {
  res.send("Black Chat is alive. Mood unstable ");
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Server running"));