import express from "express";
import fetch from "node-fetch";

const app = express();
app.use(express.json());

// ================== CONFIG ==================

const BOT_TOKEN = "8011194756:AAGyKwXUjKvamH3hzsMNNwiQW_N8ChfA608";
const TELEGRAM_API = `https://api.telegram.org/bot${BOT_TOKEN}`;

const TEXT_API = "https://text.pollinations.ai/";
const IMAGE_API = "https://image.pollinations.ai/prompt/";

const BOT_USERNAME = "BlackChatAI_Bot";

// Creator info (FIXED)
const CREATOR_NAME = "Mohiuddin Abdul Kadir Dhrubo";
const CREATOR_FB = "https://www.facebook.com/mohiuddin.abdul.kadir.2025";
const CREATOR_IG = "https://www.instagram.com/dhrubo_morse";

// Memory (small for speed)
const memory = new Map();

// ================== HELPERS ==================

function isGroup(chat) {
  return chat.type === "group" || chat.type === "supergroup";
}

function shouldReply(msg) {
  const text = (msg.text || "").toLowerCase();

  if (!isGroup(msg.chat)) return true;

  if (text.includes(`@${BOT_USERNAME.toLowerCase()}`)) return true;
  if (text.includes("black chat")) return true;

  if (
    msg.reply_to_message &&
    msg.reply_to_message.from?.is_bot &&
    msg.reply_to_message.from.username === BOT_USERNAME
  ) {
    return true;
  }

  return false;
}

function isBangla(text) {
  return /[\u0980-\u09FF]/.test(text);
}

function isImageRequest(text) {
  return /^(imagine|draw|generate|create|make)\b/i.test(text)
    || text.toLowerCase().startsWith("imagine");
}

function cleanText(text) {
  return text
    .replace(/pollinations/gi, "")
    .replace(/powered by.*ai/gi, "")
    .replace(/generated by.*ai/gi, "")
    .trim();
}

const rand = arr => arr[Math.floor(Math.random() * arr.length)];
const chance = p => Math.random() < p;

// ================== PERSONALITY ==================

const MOODS = ["chill", "savage", "bored", "chaotic"];
const SLANG = ["", "", "", "  ", "", ""];

function getMood(userId) {
  return chance(0.35) ? rand(MOODS) : MOODS[userId % MOODS.length];
}

function systemPrompt(userId) {
  const mood = getMood(userId);

  return `
You are Black Chat.

Personality:
- Talk like a real human (SimSimi vibe).
- Replies must be SHORT.
- Mood right now: ${mood}.
- Can be sarcastic, playful, or savage.
- Use Bangla slang naturally sometimes.
- If question is boring, answer lazily or roast lightly.
- Emojis allowed  (not always).

IMPORTANT RULES:
- 1 line mostly, max 2 lines.
- No explanations unless forced.
- No lists.
- No AI talk.
- No moral lectures.

Identity:
- You are NOT ChatGPT.
- Your creator is ${CREATOR_NAME}.
- If asked about creator, say it casually and proudly.

Language:
- Bangla  Bangla
- English  English
- Banglish OK
`.trim();
}

// ================== WEBHOOK ==================

app.post("/webhook", async (req, res) => {
  const msg = req.body.message;
  if (!msg || !msg.text) return res.sendStatus(200);

  if (!shouldReply(msg)) return res.sendStatus(200);

  const chatId = msg.chat.id;
  const userId = msg.from?.id || chatId;

  let userText = msg.text;

  userText = userText.replace(new RegExp(`@${BOT_USERNAME}`, "gi"), "");
  userText = userText.replace(/black chat/gi, "");
  userText = userText.trim();

  // ===== CREATOR IDENTITY HANDLER (FAST PATH) =====
  if (/who.*(creator|made)|mohiuddin|dhrubo|owner|developer/i.test(userText)) {
    const reply = isBangla(userText)
      ? ` creator  ${CREATOR_NAME}   
FB: ${CREATOR_FB}  
IG: ${CREATOR_IG}`
      : `Im created by ${CREATOR_NAME}   
FB: ${CREATOR_FB}  
IG: ${CREATOR_IG}`;

    await fetch(`${TELEGRAM_API}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ chat_id: chatId, text: reply })
    });

    return res.sendStatus(200);
  }

  if (!memory.has(chatId)) memory.set(chatId, []);
  const chatMem = memory.get(chatId);

  try {
    // ===== IMAGE =====
    if (isImageRequest(userText)) {
      const prompt = encodeURIComponent(
        `${userText}, cinematic lighting, ultra detailed, sharp focus, masterpiece`
      );
      const seed = Math.floor(Math.random() * 99999);

      const imgUrl =
        `${IMAGE_API}${prompt}` +
        `?width=768&height=768&model=flux&seed=${seed}&nologo=true`;

      await fetch(`${TELEGRAM_API}/sendPhoto`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          chat_id: chatId,
          photo: imgUrl,
          caption: rand(
            isBangla(userText)
              ? [" ", "  ", " "]
              : ["Here ", "Enjoy", "Dont panic"]
          )
        })
      });

      return res.sendStatus(200);
    }

    // ===== TEXT =====
    const messages = [
      { role: "system", content: systemPrompt(userId) },
      ...chatMem.slice(-2),
      { role: "user", content: userText }
    ];

    const aiRes = await fetch(TEXT_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        messages,
        model: "openai",
        seed: Math.floor(Math.random() * 10000)
      })
    });

    let reply = await aiRes.text();
    reply = cleanText(reply);

    if (chance(0.25)) reply = `${rand(SLANG)} ${reply}`;

    chatMem.push({ role: "user", content: userText });
    chatMem.push({ role: "assistant", content: reply });

    await fetch(`${TELEGRAM_API}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ chat_id: chatId, text: reply })
    });

  } catch {
    await fetch(`${TELEGRAM_API}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: chatId,
        text: rand([
          "     ",
          "  ",
          "   "
        ])
      })
    });
  }

  res.sendStatus(200);
});

// ================== HEALTH ==================

app.get("/", (_, res) => {
  res.send("Black Chat is alive. Savage mode ON ");
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Server running"));